import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Auth0Provider } from '@auth0/nextjs-auth0'
import Script from 'next/script'
import { ClerkProvider } from '@clerk/nextjs'

const geistSans = localFont({
	src: '../fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: '../fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<head>
					{/* <Script
						src="https://web.cmp.usercentrics.eu/modules/autoblocker.js"
						strategy="beforeInteractive"
					/>
					<Script
						id="usercentrics-cmp"
						src="https://web.cmp.usercentrics.eu/ui/loader.js"
						data-settings-id="gVI-vFm7-FZEgj"
						async
						strategy="afterInteractive"
					/> */}
				</head>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<Auth0Provider>{children}</Auth0Provider>
				</body>
			</html>
		</ClerkProvider>
	)
}
